sudo: required

services:
  - docker

git:
  submodules: false

before_install:
- git submodule update --init --recursive
- /bin/sh -c "WORKSPACE=$(pwd)/arvados ./jenkins/run-build-packages-all-targets.sh --target=ubuntu1204"

